[workspace]
resolver = "2"
members = [ "asn1", "cli", "der", "pem", "tsumiki" , "x509"]

[workspace.package]
version = "0.0.1"
authors = [ "terassyi" ]
edition = "2024"
rust-version = "1.86.0"

[workspace.dependencies]
chrono = { version = "0.4.42", features = ["serde"] }
thiserror = "2.0.17"
rstest = "0.26.1"
