[package]
name = "pem"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "PEM related crate"

[dependencies]
base64.workspace = true
regex = "1.11.1"
thiserror ={ workspace = true }

tsumiki = { path = "../tsumiki" }

[dev-dependencies]
rstest ={ workspace = true }
