[package]
name = "asn1"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
chrono = { workspace = true }
der = { path = "../der" }
num-bigint = "0.4.6"
num-traits = "0.2"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = { workspace = true }
tsumiki ={ path = "../tsumiki" }

[dev-dependencies]
pem = { path = "../pem" }
rstest = { workspace = true }
serde_json = "1.0.147"
