[package]
name = "x509"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
asn1 = { path = "../asn1" }
chrono = { workspace = true }
der = { path = "../der" }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.147"
thiserror = { workspace = true }
tsumiki = { path = "../tsumiki" }

[dev-dependencies]
der = { path = "../der" }
pem = { path = "../pem" }
rstest.workspace = true
