name: Cargo Update

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  cargo-update:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/cargo-update
        id: update
      - uses: peter-evans/create-pull-request@v7
        if: steps.update.outputs.changed == 'true'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: chore/cargo-update
          delete-branch: true
          title: 'chore(deps): cargo update'
          body: 'Automated `cargo update` to update `Cargo.lock` dependencies.'
          commit-message: 'chore(deps): cargo update'
          labels: dependencies
          signoff: true
