[package]
name = "der"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "DER related crate"

[dependencies]
pem = { path = "../pem" }
nom = "8.0.0"
thiserror = { workspace = true }
tsumiki = { path = "../tsumiki" }

[dev-dependencies]
rstest = { workspace = true }
